export const ACTIONS = {
  MEALS: {
    CREATE: 'CREATE_MEAL',
    REMOVE: 'REMOVE_MEAL',
    ATTACH_FOOD: 'ATTACH_FOODS_TO_MEAL'
  },
  FOODS: {
    CREATE: 'CREATE_FOOD',
    REMOVE: 'REMOVE_FOOD'
  },
  NOTIFICATIONS: {
    CREATE: 'CREATE_NOTIFICATION',
    REMOVE: 'REMOVE_NOTIFICATION'
  }
}
